NopHoSoMotCuaZaLo/Controllers/NopHoSoZaLoController.cs
using Aspose.Words;
using BitMiracle.Docotic.Pdf;
using Microsoft.Office.Interop.Word;
using Newtonsoft.Json;
using NopHoSoMotCuaZaLo.Models;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Services;
using System.Web.Script.Serialization;
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using DocumentFormat.OpenXml.Wordprocessing;
using static NopHoSoMotCuaZaLo.Models.ZaloInfomation;
using System.Xml;
using Run = DocumentFormat.OpenXml.Wordprocessing.Run;
using BookmarkStart = DocumentFormat.OpenXml.Wordprocessing.BookmarkStart;
using WordToPDF;
using Format = NopHoSoMotCuaZaLo.Models.Format;
using System.Diagnostics;

namespace NopHoSoMotCuaZaLo.Controllers
{
    public class NopHoSoZaLoController : Controller
    {
        String pathUploadFTP = ConfigurationManager.AppSettings["pathUploadFTP"];
        String ftpServerIP = ConfigurationManager.AppSettings["ftpServerIP"];
        String ftpUserID = ConfigurationManager.AppSettings["ftpUserID"];
        String ftpPassword = ConfigurationManager.AppSettings["ftpPassword"];
        String messktDidong = ConfigurationManager.AppSettings["messktDidong"];
        String messktFiletailen = ConfigurationManager.AppSettings["messktFiletailen"];
        String nameHinhThuc1 = ConfigurationManager.AppSettings["nameHinhThuc1"];
        String nameHinhThuc2 = ConfigurationManager.AppSettings["nameHinhThuc2"];
        String tokenZalo = ConfigurationManager.AppSettings["ToKenkeyZalo"];
        String messZalo = ConfigurationManager.AppSettings["messZaloTC"];
        String messBC = ConfigurationManager.AppSettings["messBCCI"];
        String CustomerCode = ConfigurationManager.AppSettings["CustomerCode"];
        String TokenkeyVNPost = ConfigurationManager.AppSettings["TokenkeyVNPost"];
        String APILink = ConfigurationManager.AppSettings["APILink"];


        ConnectDataDichVuCongDataContext dataDichvucong = new ConnectDataDichVuCongDataContext();
        ConnectDataFpt1gatetayninhDataContext dataFpt1gatetayninh = new ConnectDataFpt1gatetayninhDataContext();
        ConnectDataFptGateMasterDataContext dataFptGatemaster = new ConnectDataFptGateMasterDataContext();


        //Lưu thông tin ảnh upload 
        public List<ArrayFile> GetArrayImg()
        {
            List<ArrayFile> file_Array = Session["File_Array"] as List<ArrayFile>;
            if (file_Array == null)
            {
                ///neu chưa tồn tại session thì tạo
                file_Array = new List<ArrayFile>();
                Session["File_Array"] = file_Array;
            }
            return file_Array;
        }
        //Lưu thông tin pdf convert
        public List<ArrayFile> GetArrayPdf()
        {
            List<ArrayFile> file_Array = Session["File_Array_Pdf"] as List<ArrayFile>;
            if (file_Array == null)
            {
                ///neu chưa tồn tại session thì tạo
                file_Array = new List<ArrayFile>();
                Session["File_Array_Pdf"] = file_Array;
            }
            return file_Array;
        }
        public List<ArrayFile> GetArrayTam()
        {
            List<ArrayFile> file_Array = Session["File_Array_Tam"] as List<ArrayFile>;
            if (file_Array == null)
            {
                ///neu chưa tồn tại session thì tạo
                file_Array = new List<ArrayFile>();
                Session["File_Array_Tam"] = file_Array;
            }
            return file_Array;
        }
        //Thêm ảnh upload vào session
        public void AddImg(string name, int idhoso)
        {
            List<ArrayFile> file_Array = GetArrayImg();
            ArrayFile name1 = file_Array.Find(n => n.utenanh == name);
            if (name1 == null)
            {
                name1 = new ArrayFile(name, idhoso);
                file_Array.Add(name1);
            }
        }
        //Thêm pdf convert vào session
        public void AddPdf(string name, int idhoso)
        {
            List<ArrayFile> file_Array = GetArrayPdf();
            ArrayFile name1 = file_Array.Find(n => n.utenanh == name);
            if (name1 == null)
            {
                name1 = new ArrayFile(name, idhoso);
                file_Array.Add(name1);
            }
        }
        public void AddTam(string name, int idhoso)
        {
            List<ArrayFile> file_Array = GetArrayTam();
            ArrayFile name1 = file_Array.Find(n => n.utenanh == name);
            if (name1 == null)
            {
                name1 = new ArrayFile(name, idhoso);
                file_Array.Add(name1);
            }
        }
        public void RemoveImg(string name)
        {
            List<ArrayFile> file_Array = GetArrayImg();
            ArrayFile name1 = file_Array.SingleOrDefault(n => n.utenanh == name);
            if (name1 != null)
            {
                file_Array.RemoveAll(n => n.utenanh == name);
            }
        }
        public void RemoveSession()
        {
            //Lay tu Session
            List<ArrayFile> file_Array = GetArrayImg();
            List<ArrayFile> file_Array_pdf = GetArrayPdf();
            file_Array.Clear();
            file_Array_pdf.Clear();
        }
        // GET: NopHoSoZaLo
        public ActionResult Index()
        {
            return View();
        }

        // GET: NopHoSoZaLo/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }
        public ActionResult SaveUploadedFile(int idHoSo)
        {
            bool isSavedSuccessfully = true;
            string fName = "";
            string finalFileName = "";
            foreach (string fileName in Request.Files)
            {
                HttpPostedFileBase file = Request.Files[fileName];
                //Save file content goes here
                fName = file.FileName;
                if (file != null && file.ContentLength > 0)
                {
                    var originalDirectory = new DirectoryInfo(string.Format("{0}FileTaiLen", Server.MapPath(@"\")));
                    string pathString = System.IO.Path.Combine(originalDirectory.ToString(), "user");
                    var fileName1 = Path.GetFileName(file.FileName);
                    string ngaythang = DateTime.Now.Ticks.ToString();
                    finalFileName = ngaythang + "_" + file.FileName;
                    bool isExists = System.IO.Directory.Exists(pathString);
                    if (!isExists)
                        System.IO.Directory.CreateDirectory(pathString);

                    var path = string.Format("{0}\\{1}", pathString, file.FileName);
                    file.SaveAs(path);
                    AddImg(file.FileName, idHoSo);
                }

            }

            if (isSavedSuccessfully)
            {
                return Json(new { Message = finalFileName });
            }
            else
            {
                return Json(new { Message = "Error in saving file" });
            }
        }
        [HttpPost]
        public ActionResult DeleteFileUpload(string FileName)
        {
            bool isDelSuccessfully = false;

            var originalDirectory = new DirectoryInfo(string.Format("{0}FileTaiLen", Server.MapPath(@"\")));
            string pathString = System.IO.Path.Combine(originalDirectory.ToString(), "user");
            var fName = "";
            fName = FileName;
            var fullPath = string.Format("{0}\\{1}", pathString, fName);
            if (System.IO.File.Exists(fullPath))
            {
                System.IO.File.Delete(fullPath);
                isDelSuccessfully = true;
                RemoveImg(fName);
            }
            if (isDelSuccessfully)
            {
                return Json(new { Message = "succesful" });
            }
            else
            {
                return Json(new { Message = "Error in del file" });
            }
        }
        public string imagesToPdf(List<ArrayFile> images)
        {
            using (PdfDocument pdf = new PdfDocument())
            {
                foreach (var item in images)
                {
                    if (images.IndexOf(item) > 0)
                        pdf.AddPage();
                    PdfPage page = pdf.Pages[images.IndexOf(item)];
                    string imagePath = item.utenanh;

                    var originalDirectory = new DirectoryInfo(string.Format("{0}FileTaiLen", Server.MapPath(@"\")));
                    string pathString = System.IO.Path.Combine(originalDirectory.ToString(), "user");
                    var fName = "";
                    fName = imagePath;
                    var fullPath = string.Format("{0}\\{1}", pathString, fName);


                    using (Bitmap bitmap = new Bitmap(fullPath))
                    {
                        //Orientation Rotate 180
                        //bitmap.RotateFlip(RotateFlipType.Rotate90FlipNone);
                        //Orientation	Rotate 90 CW
                        //bitmap.RotateFlip(RotateFlipType.Rotate90FlipNone);
                        RotateImg.ExifRotate(bitmap);
                        PdfImage pdfImage = pdf.AddImage(bitmap);
                        page.Width = pdfImage.Width;
                        page.Height = pdfImage.Height;
                        page.Canvas.DrawImage(pdfImage, 0, 0);

                    }
                }
                var originalDirectory1 = new DirectoryInfo(string.Format("{0}FileTaiLen", Server.MapPath(@"\")));
                string pathString1 = System.IO.Path.Combine(originalDirectory1.ToString(), "user");
                var fileName1 = Path.GetFileName("HosoKemTheo.pdf");
                string ngaythang = DateTime.Now.Ticks.ToString();

NopHoSoMotCuaZaLo/Views/NopHoSoZaLo/DanhSachHuyen.cshtml
@model IEnumerable<NopHoSoMotCuaZaLo.Models.Son_GetQuanHuyen>

@{
    ViewBag.Title = "Lựa Chọn Huyện";
    Layout = "~/Views/Shared/_LayoutNopHoSoZaLo.cshtml";
}

<div class="w3-content" style="max-width:1532px;">
    <div class="w3-padding w3-col l6 m8">
        <div class="w3-container w3-red">
            <h2>Nộp hồ sơ qua mạng</h2>
        </div>
        <div class="w3-container w3-white w3-padding-16">
            <div class="w3-row-padding" style="margin:0 -16px;">
                
                <div class="w3-half">
                    <h5>Chọn huyện cần nộp hồ sơ</h5>
                </div>
            </div>
        </div>
    </div>
    <div class="w3-row-padding w3-padding-16">

        @foreach (var item in Model)
        {
            <div class="w3-third w3-margin-bottom" >
                @*<img src="/w3images/room_single.jpg" alt="Norway" style="width:100%">*@
                <div class="w3-container w3-white" style="text-align: center;">
                    <h3>
                        @Html.ActionLink(item.TenDonVi, "Create", "NopHoSoZaLo", new { donvi = item.DonViID,loaihs = ViewBag.LLHS, linhvuc = ViewBag.LLV }, htmlAttributes: new
                   { style = " text-decoration: none " })
                                            </h3>
        
                    @*<button class="w3-button w3-block w3-black w3-margin-bottom">Nộp hồ sơ</button>*@
                </div>
            </div>
        }
    </div>

</div>

    <!-- Footer -->
    <footer class="w3-padding-32 w3-black w3-center w3-margin-top">
        <h5>Dịch vụ công Tây Ninh</h5>
        @*<p>Powered by <a href="https://dichvucong.tayninh.gov.vn/" target="_blank" class="w3-hover-text-green">Dịch vụ công Tây Ninh</a></p>*@
    </footer>

NopHoSoMotCuaZaLo/Views/NopHoSoZaLo/Desktopdevice.cshtml
@{
    ViewBag.Title = "Desktopdevice";
    Layout = "~/Views/Shared/_LayoutNopHoSoZaLo.cshtml";
}

<h2>You are using a Desktop device.</h2>

NopHoSoMotCuaZaLo/Views/NopHoSoZaLo/Edit.cshtml
@model NopHoSoMotCuaZaLo.FilterConfig

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutNopHoSoZaLo.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>FilterConfig</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NopHoSoMotCuaZaLo/Views/NopHoSoZaLo/KetQua.cshtml
@{
    ViewBag.Title = "KetQua";
    Layout = "~/Views/Shared/_LayoutNopHoSoZaLo.cshtml";
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<!-- Page content -->
<div class="w3-content" style="max-width:1532px;">

    <div class="w3-panel w3-red w3-leftbar w3-padding-32">
        <h2><i class="fa fa-info w3-deep-orange w3-padding w3-margin-right"></i>Nộp hồ sơ thành công</h2>
    </div>

    <div class="w3-container">
        <h3>@ViewBag.ThongTinTen</h3>
        <h5>Điện thoại: @ViewBag.ThongTinDT đã nộp qua @ViewBag.ThongTinHinhThuc thành công</h5>
    </div>

</div>

<!-- Footer -->
<footer class="w3-padding-32 w3-black w3-center w3-margin-top">
    <h5>Dịch vụ công Tây Ninh</h5>
    @*<p>Powered by <a href="https://dichvucong.tayninh.gov.vn/" target="_blank" class="w3-hover-text-green">Dịch vụ công Tây Ninh</a></p>*@
</footer>

NopHoSoMotCuaZaLo/Views/NopHoSoZaLo/LinkXaPhuong.cshtml
@model NopHoSoMotCuaZaLo.Models.DM_DONVI

@Html.ActionLink(Model.TenDonVi, "Create", "NopHoSoZaLo", new { donvi = Model.DonViID, loaihs = ViewBag.LLHS, linhvuc = ViewBag.LLV }, htmlAttributes: new
{ style = " text-decoration: none " })

NopHoSoMotCuaZaLo/Views/NopHoSoZaLo/XaPhuong.cshtml
@model IEnumerable<NopHoSoMotCuaZaLo.Models.DM_DONVI>
@{
    ViewBag.Title = "Lựa Chọn Xã";
    Layout = "~/Views/Shared/_LayoutNopHoSoZaLo.cshtml";
}


<div class="w3-content" style="max-width:1532px;">
    <div class="w3-padding w3-col l6 m8">
        <div class="w3-container w3-red">
            <h2>Nộp hồ sơ qua mạng</h2>
        </div>
        <div class="w3-container w3-white w3-padding-16">
            <div class="w3-row-padding" style="margin:0 -16px;">

                <div class="w3-half">
                    <h5>Chọn xã/ phường cần nộp hồ sơ</h5>
                </div>
            </div>
        </div>
    </div>
    <div class="w3-row-padding w3-padding-16">

        @foreach (var item in Model)
        {
            <div class="w3-third w3-margin-bottom">
                @*<img src="/w3images/room_single.jpg" alt="Norway" style="width:100%">*@
                <div class="w3-container w3-white" style="text-align: center;">
                    <h3>
                        @Html.ActionLink(item.TenDonVi, "Create", "NopHoSoZaLo", new { donvi = item.DonViID, loaihs = ViewBag.LLHS, linhvuc = ViewBag.LLV }, htmlAttributes: new
{ style = " text-decoration: none " })
                        @*@Html.Action("LinkXaPhuong", "NopHoSoZaLo", new { tenxaphuong = item.TenPhuong, idquan = item.QuanID, loaihs = ViewBag.LLHS, linhvuc = ViewBag.LLV })*@
                    </h3>

                    @*<button class="w3-button w3-block w3-black w3-margin-bottom">Nộp hồ sơ</button>*@
                </div>
            </div>
        }
    </div>

</div>

<!-- Footer -->
<footer class="w3-padding-32 w3-black w3-center w3-margin-top">
    <h5>Dịch vụ công Tây Ninh</h5>
    @*<p>Powered by <a href="https://dichvucong.tayninh.gov.vn/" target="_blank" class="w3-hover-text-green">Dịch vụ công Tây Ninh</a></p>*@
</footer>

NopHoSoMotCuaZaLo/Views/NopHoSoZaLo/XaPhuongCap1.cshtml
@model IEnumerable<NopHoSoMotCuaZaLo.Models.DMQUAN>
@{
    ViewBag.Title = "Lựa Chọn Huyện";
    Layout = "~/Views/Shared/_LayoutNopHoSoZaLo.cshtml";
}


<div class="w3-content" style="max-width:1532px;">
    <div class="w3-padding w3-col l6 m8">
        <div class="w3-container w3-red">
            <h2>Nộp hồ sơ qua mạng</h2>
        </div>
        <div class="w3-container w3-white w3-padding-16">
            <div class="w3-row-padding" style="margin:0 -16px;">

                <div class="w3-half">
                    <h5>Chọn Huyện cần nộp hồ sơ</h5>
                </div>
            </div>
        </div>
    </div>
    <div class="w3-row-padding w3-padding-16">

        @foreach (var item in Model)
        {
            <div class="w3-third w3-margin-bottom">
                @*<img src="/w3images/room_single.jpg" alt="Norway" style="width:100%">*@
                <div class="w3-container w3-white" style="text-align: center;">
                    <h3>
                        @Html.ActionLink(item.TenQuan, "XaPhuong", "NopHoSoZaLo", new { idquan = item.QuanID,loaihs=ViewBag.LLHS,linhvuc=ViewBag.LLV }, htmlAttributes: new
                   { style = " text-decoration: none " })
                    </h3>

                    @*<button class="w3-button w3-block w3-black w3-margin-bottom">Nộp hồ sơ</button>*@
                </div>
            </div>
        }
    </div>

</div>

<!-- Footer -->
<footer class="w3-padding-32 w3-black w3-center w3-margin-top">
    <h5>Dịch vụ công Tây Ninh</h5>
    <p>@*Powered by <a href="https://dichvucong.tayninh.gov.vn/" target="_blank" class="w3-hover-text-green">Dịch vụ công Tây Ninh</a>*@</p>
</footer>